{"name": "Orders list get failed for non auth user test", "status": "passed", "start": 1732715154999, "stop": 1732715156830, "uuid": "a25ca897-837f-4fec-8cc4-f558d6314973", "historyId": "f128b8750557e1aa9de6e07d7bc70b44", "testCaseId": "f128b8750557e1aa9de6e07d7bc70b44", "fullName": "tests.test_get_user_orders.TestGetOrders#test_get_orders_non_auth_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_orders"}, {"name": "subSuite", "value": "TestGetOrders"}, {"name": "host", "value": "ast24help1c2"}, {"name": "thread", "value": "11252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_orders"}]}