{"name": "Creation User Clone Error", "status": "passed", "start": 1732715243215, "stop": 1732715245608, "uuid": "dbc912c5-7adc-4d96-92c9-2bb14504acbb", "historyId": "85009a631c2312d2372f1df0533791f8", "testCaseId": "85009a631c2312d2372f1df0533791f8", "fullName": "tests.test_user_creation.TestCreateUser#test_create_user_clone_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_creation"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "ast24help1c2"}, {"name": "thread", "value": "11252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_creation"}]}